sudo: false
cache:
  directories:
    - "$HOME/.m2"
language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
script:
  - mvn -B -T2 -fae clean install
notifications:
  email: false
  on_failure: never
